spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
service:
  authorization:
    secret-key: ${AUTHORIZATION_SECRET_KEY:g8rrLgXxe3/OF+mwPQGINe5pxxh5AQddN6gNFE3iueY=}
    access-timeout: ${AUTHORIZATION_ACCESS_TIMEOUT:86400000}
    refresh-timeout: ${AUTHORIZATION_REFRESH_TIMEOUT:604800000}
