spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: ${HIBERNATE_DIALECT}
springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    enabled: ${SWAGGER_UI_ENABLED}
service:
  authorization:
    secret-key: ${AUTHORIZATION_SECRET_KEY}
    access-timeout: ${AUTHORIZATION_ACCESS_TIMEOUT}
    refresh-timeout: ${AUTHORIZATION_REFRESH_TIMEOUT}
  firebase:
    resource: ${FIREBASE_RESOURCE:classpath:firebase/firebase.json}
    scopes:
      - https://www.googleapis.com/auth/cloud-platform