
name: Deploy to S3 and Lambda

on:
  push:
    branches: ["김영훈"]

env:
  AWS_REGION_SEOUL: ap-northeast-2 
  AWS_REGION_US: us-east-1
  BUCKET_NAME: chusome.com
  FUNCTION_NAME: chu-some-chu=some # set this to the name of the container in the
  # containerDefinitions section of your task definition

jobs:
  deploy_static:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION_SEOUL }}
    - name: Upload static files to S3
      run: |
        aws s3 cp ./static/* s3://${{env.BUCKET_NAME}}/


  # deploy_core:
  #   name: Deploy to lambda
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v2
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: ${{ env.AWS_REGION }}
  #   - name: Compress python code to zip
  #     run: | 
  #       cd serchInstance
  #       zip -r serchInstance.zip ./*
  #       aws s3 cp serchInstance.zip s3://${{env.BUCKET_NAME}}/serchInstance.zip
  #       aws lambda update-function-code --function-name ${{env.FUNCTION_NAME}}  --s3-bucket ${{env.BUCKET_NAME}} --s3-key serchInstance.zip
